import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { SessionProvider } from "next-auth/react";
import HomeView from "@/components/views/Home";
import HomeLayout from "@/components/layouts/HomeLayout";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    if (isDarkMode) {
      document.documentElement.classList.add("dark-theme");
    } else {
      document.documentElement.classList.remove("dark-theme");
    }
  }, [isDarkMode]);

  const toggleTheme = () => {
    setIsDarkMode(!isDarkMode);
  };

  useEffect(() => {
    const getUsers = async () => {
      // const users = await userServices.getUser();
      console.log("1");
    };
    getUsers();
  });

  return (
    <SessionProvider>
      <Head>
        <title>TodoKu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        ></link>
      </Head>
      <main className={inter.className}>
        <HomeLayout>
          <HomeView />
        </HomeLayout>
      </main>
    </SessionProvider>
  );
}
